pipeline {
    agent none
    stages {
        stage('Build') {
            agent any
            steps {
                withEnv(["HOME=${env.WORKSPACE}"]) {
                    sh 'python3 -m pip install --upgrade pip'
                    sh '/Users/renancso/.jenkins/workspace/hackone-test-pipeline@2/Library/Python/3.9/bin/pip install pytest'
                    sh 'python3 -m py_compile sources/add2vals.py sources/calc.py'
                }
            }
        }
        stage('Test') {
            agent any
            steps {
                withEnv(["HOME=${env.WORKSPACE}"]) {
                    sh 'pytest --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
                }
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
    }
}
